baseURL = 'https://datamktkorea.github.io/dmk-tech-blog/'
languageCode = 'ko-kr'
title = 'DMK TECH BLOG'

[params]
  subtitle = '데이터마케팅코리아 개발팀의 기록 일지'
  logoUrl = '/images/dmk-logo.png'

[taxonomies]
  tag = 'tags'

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

canonifyURLs = true
relativeURLs = true
enableRobotsTXT = true